version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'fix'
      prefix-development: 'chore'
      include: 'scope'
    open-pull-requests-limit: 20
    groups:
      major-dependencies:
        patterns:
          - '*'
        update-types:
          - 'major'
        dependency-type: 'production'
      minor-patch-dependencies:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
        dependency-type: 'production'
      major-dev-dependencies:
        patterns:
          - '*'
        update-types:
          - 'major'
        dependency-type: 'development'
      minor-patch-dev-dependencies:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
        dependency-type: 'development'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'fix'
      prefix-development: 'chore'
      include: 'scope'
